# Generated by Django 4.0.2 on 2022-03-05 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=50)),
                ('categories', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='course.category')),
            ],
            options={
                'db_table': 'channel',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_description', models.TextField()),
                ('course_details', models.TextField()),
                ('course_creator', models.CharField(max_length=500)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('course_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('course_image_url', models.URLField(blank=True, null=True)),
                ('course_channel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_channel', to='course.channel')),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
